### ISSUE TITLE
`msg` not defined in simplest_notebook/__init__.py

### ISSUE THREAD

**Issue by geoffbacon** [yuvipanda/simplest-notebook#2]
I installed simplest-notebook locally (`pip install simplest-notebook`), tried to open it (`jupyter simplest-notebook`) but get a NameError because `msg` is not defined [on line 94](https://github.com/yuvipanda/simplest-notebook/blob/992987ce23b31c3853e397f0802ce5449d1f49ba/simplest_notebook/__init__.py#L94).

Traceback (most recent call last):
  File "/Users/bacon/miniconda/bin/jupyter-simplest-notebook", line 10, in <module>
    sys.exit(main())
  File "/Users/bacon/miniconda/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/bacon/miniconda/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</Users/bacon/miniconda/lib/python3.7/site-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/Users/bacon/miniconda/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/bacon/miniconda/lib/python3.7/site-packages/notebook/notebookapp.py", line 1633, in initialize
    self.init_server_extensions()
  File "/Users/bacon/miniconda/lib/python3.7/site-packages/simplest_notebook/__init__.py", line 94, in init_server_extensions
    self.log.warn(msg)
NameError: name 'msg' is not defined

**Comment by yuvipanda** [comment]
<3 thanks for reporting this, @geoffbacon! fixed.

**Comment by yuvipanda** [comment]
I've uploaded v0.0.9 to PyPI now. Let me know if that works for you.

**Comment by geoffbacon** [comment]
Works! Thanks!
